//! Deterministic SYNTHETIC / constructed Curve Recovery demo.
//! Fixture outputs are generated by the engines, not hand-entered.

use crate::error::PlanStatus;
use crate::flight::{
    estimate_bit, evaluate_scenario, qualify_memory, score_forecasts, BhaMemory, BhaRun,
    DrillingSegment, MemorySample, OperatingConstraints, PathClass, ScenarioDecision,
    ScenarioInput, ToolfaceBasis,
};
use crate::plan::{solve_slant_2d, PlanSolveResult, Slant2dInput};
use crate::project::{
    project_hold, Attitude, DlsRefLength, HoldRequest, SlideMode, SlideRotateSeg,
};
use crate::sections::CorridorTol;
use crate::sections::SolveUnknown;
use delve_core::{StationClass, UnitSystem};
use serde::{Deserialize, Serialize};

pub const DEMO_NAME: &str = "Curve Recovery — Plan & Flight Deck";
pub const DEMO_MARK: &str = "SYNTHETIC / constructed";

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DemoSurvey {
    pub md: f64,
    pub inc_deg: f64,
    pub azi_deg: f64,
    pub accepted: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CurveRecoveryDemo {
    pub name: String,
    pub mark: String,
    pub plan: PlanSolveResult,
    pub surveys: Vec<DemoSurvey>,
    pub held_out: DemoSurvey,
    pub bha: BhaRun,
    pub prior_samples: Vec<MemorySample>,
    pub memory: BhaMemory,
    pub segments: Vec<DrillingSegment>,
    pub constraints: OperatingConstraints,
    pub corridor: CorridorTol,
    pub scenarios: Vec<ScenarioInput>,
    pub last_accepted: Attitude,
}

pub fn curve_recovery_demo() -> CurveRecoveryDemo {
    let plan = solve_slant_2d(&Slant2dInput {
        unit: UnitSystem::Imperial,
        target_tvd: 4500.0,
        target_disp: 1000.0,
        target_azi_deg: 45.0,
        kop: Some(650.0),
        dls_display: Some(3.0),
        dls_ref: DlsRefLength::Per100Ft,
        hold_inc_deg: None,
        solve: SolveUnknown::HoldAngle,
    })
    .expect("demo plan");

    // Accepted surveys trend away from the 45° plan (walking right / higher AZI).
    let surveys = vec![
        DemoSurvey {
            md: 0.0,
            inc_deg: 0.0,
            azi_deg: 45.0,
            accepted: true,
        },
        DemoSurvey {
            md: 650.0,
            inc_deg: 0.0,
            azi_deg: 45.0,
            accepted: true,
        },
        DemoSurvey {
            md: 1200.0,
            inc_deg: 8.0,
            azi_deg: 52.0,
            accepted: true,
        },
        DemoSurvey {
            md: 1800.0,
            inc_deg: 14.0,
            azi_deg: 58.0,
            accepted: true,
        },
        DemoSurvey {
            md: 2400.0,
            inc_deg: 16.2,
            azi_deg: 62.0,
            accepted: true,
        },
    ];
    // Hidden held-out truth uses a distinct synthetic response and must never enter forecasts.
    let held_out = DemoSurvey {
        md: 2495.0,
        inc_deg: 17.4,
        azi_deg: 64.5,
        accepted: false,
    };

    let bha = BhaRun {
        id: "demo-bha".into(),
        hole_id: "demo-hole".into(),
        name: "Demo motor revision 1".into(),
        configuration_revision: 1,
        start_md: 2000.0,
        end_md: None,
        motor_id: "SYN-1".into(),
        motor_model: "synthetic 1.5°".into(),
        bend_setting: "1.5".into(),
        bit_size: 8.5,
        hole_size: 8.75,
        sensor_to_bit: 52.0,
        hole_section: "8.5 in".into(),
        formation_tag: "synthetic".into(),
        toolface_basis: ToolfaceBasis::Gravity,
        slide_yield_low: 6.0,
        slide_yield_nom: 8.0,
        slide_yield_high: 10.0,
        rotary_dls: 0.3,
        rotary_tf_deg: 90.0,
        yield_ref: DlsRefLength::Per100Ft,
        notes: DEMO_MARK.into(),
    };

    let prior_samples: Vec<MemorySample> = (0..5)
        .map(|i| MemorySample {
            id: format!("s{i}"),
            bha_revision: 1,
            start_bit_md: 2100.0 + i as f64 * 40.0,
            end_bit_md: 2120.0 + i as f64 * 40.0,
            mode: SlideMode::Slide,
            included: true,
            reason: String::new(),
            fitted_yield: Some(7.6 + 0.15 * i as f64),
            residual_deg: Some(0.18),
        })
        .collect();
    let memory = qualify_memory(&bha, &prior_samples, 0.5, 10.0);

    let last_md = 2400.0;
    let segments = vec![
        DrillingSegment {
            id: "blind".into(),
            bha_id: bha.id.clone(),
            start_bit_md: last_md,
            end_bit_md: last_md + 52.0,
            mode: SlideMode::Rotate,
            toolface_deg: None,
            toolface_basis: ToolfaceBasis::Gravity,
            wob: None,
            flow: None,
            rpm: None,
            rop: None,
            started_at: Some("2026-08-28T08:00".into()),
            ended_at: Some("2026-08-28T08:40".into()),
            source: "synthetic".into(),
        },
        DrillingSegment {
            id: "to-bit".into(),
            bha_id: bha.id.clone(),
            start_bit_md: last_md + 52.0,
            end_bit_md: last_md + 95.0,
            mode: SlideMode::Rotate,
            toolface_deg: None,
            toolface_basis: ToolfaceBasis::Gravity,
            wob: None,
            flow: None,
            rpm: None,
            rop: None,
            started_at: Some("2026-08-28T08:40".into()),
            ended_at: Some("2026-08-28T09:10".into()),
            source: "synthetic".into(),
        },
    ];

    let constraints = OperatingConstraints {
        stand_length: 93.0,
        max_slide_per_stand: 50.0,
        min_useful_slide: 8.0,
        max_dls: 12.0,
        max_yield: 12.0,
    };
    let corridor = CorridorTol {
        up_down: 15.0,
        left_right: 15.0,
    };

    let scenarios = vec![
        ScenarioInput {
            id: "hold".into(),
            name: "Hold".into(),
            method: "hold".into(),
            added_md: 93.0,
            dls_display: None,
            toolface_deg: None,
            build_deg_per_ref: None,
            turn_deg_per_ref: None,
            slide_yield: None,
            segments: vec![],
        },
        ScenarioInput {
            id: "short".into(),
            name: "Short correction".into(),
            method: "slide_rotate".into(),
            added_md: 93.0,
            dls_display: Some(10.0),
            toolface_deg: Some(270.0),
            build_deg_per_ref: None,
            turn_deg_per_ref: None,
            slide_yield: Some(10.0),
            segments: vec![
                SlideRotateSeg {
                    mode: SlideMode::Slide,
                    length: 28.0,
                    toolface_deg: 270.0,
                    slide_yield_dls: 10.0,
                    rotary_dls: 0.3,
                    rotary_tf_deg: 90.0,
                    dls_ref: DlsRefLength::Per100Ft,
                },
                SlideRotateSeg {
                    mode: SlideMode::Rotate,
                    length: 65.0,
                    toolface_deg: 0.0,
                    slide_yield_dls: 10.0,
                    rotary_dls: 0.3,
                    rotary_tf_deg: 90.0,
                    dls_ref: DlsRefLength::Per100Ft,
                },
            ],
        },
        ScenarioInput {
            id: "long".into(),
            name: "Longer / gentler".into(),
            method: "slide_rotate".into(),
            added_md: 93.0,
            dls_display: Some(7.0),
            toolface_deg: Some(270.0),
            build_deg_per_ref: None,
            turn_deg_per_ref: None,
            slide_yield: Some(7.0),
            segments: vec![
                SlideRotateSeg {
                    mode: SlideMode::Slide,
                    length: 48.0,
                    toolface_deg: 270.0,
                    slide_yield_dls: 7.0,
                    rotary_dls: 0.3,
                    rotary_tf_deg: 90.0,
                    dls_ref: DlsRefLength::Per100Ft,
                },
                SlideRotateSeg {
                    mode: SlideMode::Rotate,
                    length: 45.0,
                    toolface_deg: 0.0,
                    slide_yield_dls: 7.0,
                    rotary_dls: 0.3,
                    rotary_tf_deg: 90.0,
                    dls_ref: DlsRefLength::Per100Ft,
                },
            ],
        },
    ];

    CurveRecoveryDemo {
        name: DEMO_NAME.into(),
        mark: DEMO_MARK.into(),
        plan,
        surveys,
        held_out,
        bha,
        prior_samples,
        memory,
        segments,
        constraints,
        corridor,
        scenarios,
        last_accepted: demo_last_accepted_attitude(),
    }
}

pub fn demo_last_accepted_attitude() -> Attitude {
    Attitude {
        md: 2400.0,
        inc_deg: 16.2,
        azi_deg: 62.0,
        north: 180.0,
        east: 320.0,
        tvd: 2385.0,
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DemoAssertions {
    pub hold_misses_corridor: bool,
    pub slide_tradeoff: bool,
    pub held_out_absent_from_memory: bool,
    pub forecasts_frozen: bool,
    pub path_classes: Vec<PathClass>,
}

pub fn assert_demo_story(demo: &CurveRecoveryDemo) -> Result<DemoAssertions, String> {
    if demo.plan.status != PlanStatus::Solved {
        return Err("demo plan must solve".into());
    }
    if demo.memory.qualified_count < 5 {
        return Err("need five qualified pre-reveal samples".into());
    }
    if demo
        .memory
        .samples
        .iter()
        .any(|s| (s.end_bit_md - demo.held_out.md).abs() < 1.0)
    {
        return Err("held-out station leaked into memory samples".into());
    }
    let sensor = demo_last_accepted_attitude();
    let est = estimate_bit(
        sensor,
        &demo.bha,
        &demo.segments,
        None,
        UnitSystem::Imperial,
    )
    .map_err(|e| e.to_string())?;
    let plan_end = demo.plan.stations.last().ok_or("no plan station")?;
    let plan_att = Attitude {
        md: plan_end.md,
        inc_deg: plan_end.inc_deg,
        azi_deg: plan_end.azi_deg,
        north: plan_end.north,
        east: plan_end.east,
        tvd: plan_end.tvd,
    };
    let hold = evaluate_scenario(
        est.bit,
        &demo.bha,
        &demo.scenarios[0],
        Some(&plan_att),
        Some(&demo.corridor),
        &demo.constraints,
        UnitSystem::Imperial,
        None,
        None,
    )
    .map_err(|e| e.to_string())?;
    let short = evaluate_scenario(
        est.bit,
        &demo.bha,
        &demo.scenarios[1],
        Some(&plan_att),
        Some(&demo.corridor),
        &demo.constraints,
        UnitSystem::Imperial,
        None,
        None,
    )
    .map_err(|e| e.to_string())?;
    let long = evaluate_scenario(
        est.bit,
        &demo.bha,
        &demo.scenarios[2],
        Some(&plan_att),
        Some(&demo.corridor),
        &demo.constraints,
        UnitSystem::Imperial,
        None,
        None,
    )
    .map_err(|e| e.to_string())?;

    let hold_off = hold
        .ud
        .unwrap_or(0.0)
        .abs()
        .max(hold.lr.unwrap_or(0.0).abs());
    let hold_misses = hold_off > demo.corridor.left_right || !hold.constraint_feasible;
    let tradeoff =
        short.max_dls > long.max_dls + 0.2 && long.slide_footage > short.slide_footage + 5.0;

    let frozen = vec![
        ("hold".into(), att_from_card(&hold)),
        ("short".into(), att_from_card(&short)),
        ("long".into(), att_from_card(&long)),
    ];
    let decision = ScenarioDecision {
        id: "demo-dec".into(),
        hole_id: "demo-hole".into(),
        accepted_survey_md: sensor.md,
        estimated_bit_md: est.derived_bit_md,
        plan_revision: 1,
        bha_id: demo.bha.id.clone(),
        bha_revision: demo.bha.configuration_revision,
        target_id: None,
        offset_hole_id: None,
        assumptions: vec![],
        constraints: demo.constraints.clone(),
        scenarios: demo.scenarios.clone(),
        selected_scenario_id: Some("short".into()),
        memory_revision: demo.memory.revision,
        memory_sample_ids: demo.memory.sample_ids.clone(),
        expected_survey_md: est.derived_bit_md - demo.bha.sensor_to_bit + 93.0,
        actual_resolution_md: None,
        scores: vec![],
        created_at: "synthetic".into(),
        resolved_at: None,
    };
    let actual = Attitude {
        md: demo.held_out.md,
        inc_deg: demo.held_out.inc_deg,
        azi_deg: demo.held_out.azi_deg,
        north: hold.future_bit.north + 12.0,
        east: hold.future_bit.east - 8.0,
        tvd: hold.future_bit.tvd + 1.0,
    };
    let scores = score_forecasts(&decision, demo.held_out.md, actual, &frozen);
    let frozen_ok = scores
        .iter()
        .all(|s| s.pre_update_memory_revision == demo.memory.revision)
        && (frozen[0].1.inc_deg - hold.future_bit.inc_deg).abs() < 1e-12;

    Ok(DemoAssertions {
        hold_misses_corridor: hold_misses,
        slide_tradeoff: tradeoff,
        held_out_absent_from_memory: true,
        forecasts_frozen: frozen_ok,
        path_classes: vec![
            PathClass::AcceptedSurvey,
            PathClass::Estimated,
            PathClass::Scenario,
        ],
    })
}

fn att_from_card(c: &crate::flight::ScenarioCard) -> Attitude {
    Attitude {
        md: c.next_sensor_md,
        inc_deg: c.next_sensor.inc_deg,
        azi_deg: c.next_sensor.azi_deg,
        north: c.next_sensor.north,
        east: c.next_sensor.east,
        tvd: c.next_sensor.tvd,
    }
}

#[allow(dead_code)]
fn _hold_ref(a: Attitude) -> Result<crate::project::ProjectionResult, crate::error::PlanError> {
    project_hold(&HoldRequest {
        start: a,
        added_md: 1.0,
        unit: UnitSystem::Imperial,
        class: StationClass::Projected,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn curve_recovery_story() {
        let demo = curve_recovery_demo();
        assert_eq!(demo.name, DEMO_NAME);
        assert_eq!(demo.mark, DEMO_MARK);
        let a = assert_demo_story(&demo).expect("demo story");
        assert!(a.held_out_absent_from_memory);
        assert!(a.forecasts_frozen);
        assert!(
            a.slide_tradeoff,
            "short vs long must trade DLS against slide footage"
        );
        assert!(
            a.hold_misses_corridor,
            "hold should miss the plan corridor under the demo walkaway"
        );
        assert!(!demo
            .surveys
            .iter()
            .any(|s| (s.md - demo.held_out.md).abs() < 1e-6 && s.accepted));
    }
}
